name: house_rental_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.3.2
  fpdart: ^1.0.0
  image_picker: ^0.8.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  lucide_icons: ^0.257.0
  go_router: ^15.1.3
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.3.2
  image_picker: ^0.8.6
  equatable: ^2.0.5


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
